apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
data:
  server.properties: |
    motd=Hurrsh Minecraft Server
    allow-flight=true
    spawn-protection=0
    max-players=20
    online-mode=true
    enable-command-block=false
    view-distance=10
    simulation-distance=10
    difficulty=normal
