apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mc-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: mc-monitor
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: metrics
    interval: 15s
